@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-header">
            <h4>{{ ucfirst(str_replace('_', ' ', $report->report_type)) }} Report</h4>
            <p class="text-muted">
                Period: {{ $report->start_date->format('Y-m-d') }} to {{ $report->end_date->format('Y-m-d') }}
            </p>
        </div>
        <div class="card-body">
            @if($report->report_type === 'profit_loss')
                @include('finance.reports.partials.profit_loss')
            @elseif($report->report_type === 'cash_flow')
                @include('finance.reports.partials.cash_flow')
            @elseif($report->report_type === 'balance_sheet')
                @include('finance.reports.partials.balance_sheet')
            @endif
        </div>
        <div class="card-footer text-muted">
            Generated by: {{ $report->user->name }} on {{ $report->created_at->format('Y-m-d H:i:s') }}
        </div>
    </div>
</div>
@endsection